theme: minima
layouts_dir:_layouts

# Teaching Experience

## SLS 1122 New Student Expeience
2017-Present
* Students identify their career, academic and personal purpose. 

## SPC 1608 Fundamentals of Speech
2023-Present
* Students learn the principles of oral communication common to speaking and listening.